### ISSUE TITLE
impose a time limit on each task!

### ISSUE THREAD

**Issue by 1fish2** [CovertLab/sisyphus#13]
Sisyphus had better impose a time limit on each task.

Ideally it'd be configurable, but no limit is no good.

See https://github.com/CovertLab/wcEcoli/pull/703#discussion_r334293021

**Comment by prismofeverything** [comment]
Agreed! Though some tasks can take days, intentionally, so I don't think we can do a general timeout. Probably need to have each task declare its timeout.

**Comment by 1fish2** [comment]
A per-task time limit is a great idea, with a default of perhaps 1 hour. (parca takes about 25 minutes.)

Furthermore, say parca-task declares a 45 minute timeout and write-metadata-task declares a 5 minute timeout. Then Gaia/Sisyphus should be able to figure out to keep the write-metadata-task's worker from auto-shutdown while the rest of the workflow awaits the parca-task. (Currently there's a workaround hack where the write-metadata-task claims to depend on the parca output.)
